import type { Metadata } from "next";
import "./globals.css";

import { BuilderProvider } from '@/lib/BuilderContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BuilderProvider>
          <div className="flex flex-grow">
            <div className="flex flex-grow">
            <main className="flex-grow">
              {children}
            </main>
          </div>
          </div>
        </BuilderProvider>
      </body>
    </html>
  );
}
